name: master deploy

permissions:
  contents: write

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Test Build
        run: |
          npm install --legacy-peer-deps
          npm run build
  build-and-deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
